#!/bin/bash

# Run the command to get the current mode
current_mode=$(sudo awcc qm | grep -oP 'Current mode: \K.*')
echo "Current mode: $current_mode"
# Check if the mode is "Gaming (G-Mode)" or not
if [[ "$current_mode" != "Gaming (G-Mode)" ]]; then
    # Mode is not Gaming (G-Mode), toggle to G-Mode
    sudo /usr/bin/awcc gt
    # Send notification for switching to Gaming Mode
    notify-send "Alienware Command Centre" "Turning on G-Mode"
    sudo /usr/bin/gamemode
else
    # Mode is Gaming (G-Mode), toggle to G-Mode
    sudo /usr/bin/awcc gt
    # Send notification for staying in Gaming Mode
    notify-send "Mode Changed" "Turning off G-Mode"
    # Run the specific bash file for Gaming mode
    sudo /usr/bin/powersave
fi

